services:
  db-user:
    image: mongo
    environment: 
      MONGO_INITDB_DATABASE: user
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    ports: 
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my-custom-network

  api-user:
    container_name: node_api_bolierplate_user
    build: 
      context: .
    ports:
      - "3004:3000"
    depends_on:
      - db-user
    networks:
      - my-custom-network

  redis-logs-user:
    image: redis
    ports:
      - "6378:6379"
    command: redis-server --appendonly yes
    networks:
      - my-custom-network
  
  mongo-seed:
    image: mongo
    container_name: node_api_bolierplate_mongo_seed
    links: 
      - db-user
    volumes: 
      - ./mongo-seed.json:/mongo-seed.json
    command: >
      bash -c "mongoimport --uri mongodb://mateusdreher:Passw0rd@db-user:27017/user --collection users --type json --file /mongo-seed.json --jsonArray && exit"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    external: true